--///////////////////////////////////////////////////////
-- Trudeau / Colors
--///////////////////////////////////////////////////////
INSERT INTO Colors -- Primary is background, secondary foreground.
        (Type,												Color)
VALUES  ('COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY',		'255,255,255,255'),
		('COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY',	'202,20,21,255'),
		('COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY2',	'202,20,21,255'),
		('COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY2',	'255,255,255,255'),
		('COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY3',	'120,0,1,255'),
		('COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY3',	'229,117,116,255'),
		('COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY4',	'229,117,116,255'),
		('COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY4',	'120,0,1,255');

INSERT INTO PlayerColors (
		Type,
		Usage, 
		PrimaryColor, 
		SecondaryColor, 
		Alt1PrimaryColor, 
		Alt1SecondaryColor, 
		Alt2PrimaryColor, 
		Alt2SecondaryColor, 
		Alt3PrimaryColor, 
		Alt3SecondaryColor)
VALUES	('LEADER_TRUDEAU',
		'Unique',
		'COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY',
		'COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY',
		'COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY2',
		'COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY2',
		'COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY3',
		'COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY3',
		'COLOR_PLAYER_TRUDEAU_CANADA_PRIMARY4',
		'COLOR_PLAYER_TRUDEAU_CANADA_SECONDARY4');